import { PrismaClient } from "@prisma/client";
import cors from "cors";
import "dotenv/config";
import express from "express";

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(
  cors({
    origin: "*",
  })
);

const prisma = new PrismaClient();

import productRoutes from "./routes/products.routes.js"
import userRoutes from "./routes/user.routes.js"
import gameRoutes from "./routes/game.routes.js"
import pokemonRoutes from "./routes/pokemon.routes.js"

app.use('/api/games', gameRoutes)
app.use('/api/products', productRoutes)
app.use('/api/users', userRoutes)
app.use('/api/pokemons', pokemonRoutes)

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});

const data = [
  {
    id: 1,
    name: "NVIDIA GeForce RTX 4090",
    brand: "NVIDIA",
    chipset: "RTX 4090",
    vram: "24GB GDDR6X",
    price: 2599,
    stock: 10,
    rating: 4.9,
    image: "https://example.com/images/rtx4090.jpg",
  },
  {
    id: 2,
    name: "NVIDIA GeForce RTX 4080 Super",
    brand: "NVIDIA",
    chipset: "RTX 4080 Super",
    vram: "16GB GDDR6X",
    price: 1899,
    stock: 15,
    rating: 4.8,
    image: "https://example.com/images/rtx4080super.jpg",
  },
  {
    id: 3,
    name: "NVIDIA GeForce RTX 4070 Ti",
    brand: "NVIDIA",
    chipset: "RTX 4070 Ti",
    vram: "12GB GDDR6X",
    price: 1099,
    stock: 20,
    rating: 4.7,
    image: "https://example.com/images/rtx4070ti.jpg",
  },
  {
    id: 4,
    name: "NVIDIA GeForce RTX 4060",
    brand: "NVIDIA",
    chipset: "RTX 4060",
    vram: "8GB GDDR6",
    price: 499,
    stock: 25,
    rating: 4.5,
    image: "https://example.com/images/rtx4060.jpg",
  },
  {
    id: 5,
    name: "NVIDIA GeForce RTX 3050",
    brand: "NVIDIA",
    chipset: "RTX 3050",
    vram: "8GB GDDR6",
    price: 329,
    stock: 30,
    rating: 4.3,
    image: "https://example.com/images/rtx3050.jpg",
  },
  {
    id: 6,
    name: "AMD Radeon RX 7900 XTX",
    brand: "AMD",
    chipset: "RX 7900 XTX",
    vram: "24GB GDDR6",
    price: 1199,
    stock: 12,
    rating: 4.8,
    image: "https://example.com/images/rx7900xtx.jpg",
  },
  {
    id: 7,
    name: "AMD Radeon RX 7900 XT",
    brand: "AMD",
    chipset: "RX 7900 XT",
    vram: "20GB GDDR6",
    price: 999,
    stock: 18,
    rating: 4.7,
    image: "https://example.com/images/rx7900xt.jpg",
  },
  {
    id: 8,
    name: "AMD Radeon RX 7800 XT",
    brand: "AMD",
    chipset: "RX 7800 XT",
    vram: "16GB GDDR6",
    price: 699,
    stock: 22,
    rating: 4.6,
    image: "https://example.com/images/rx7800xt.jpg",
  },
  {
    id: 9,
    name: "AMD Radeon RX 7700 XT",
    brand: "AMD",
    chipset: "RX 7700 XT",
    vram: "12GB GDDR6",
    price: 599,
    stock: 20,
    rating: 4.5,
    image: "https://example.com/images/rx7700xt.jpg",
  },
  {
    id: 10,
    name: "AMD Radeon RX 7600",
    brand: "AMD",
    chipset: "RX 7600",
    vram: "8GB GDDR6",
    price: 299,
    stock: 35,
    rating: 4.4,
    image: "https://example.com/images/rx7600.jpg",
  },
  {
    id: 11,
    name: "Intel Arc A770",
    brand: "Intel",
    chipset: "Arc A770",
    vram: "16GB GDDR6",
    price: 349,
    stock: 25,
    rating: 4.2,
    image: "https://example.com/images/arcc770.jpg",
  },
  {
    id: 12,
    name: "Intel Arc A750",
    brand: "Intel",
    chipset: "Arc A750",
    vram: "8GB GDDR6",
    price: 249,
    stock: 30,
    rating: 4.1,
    image: "https://example.com/images/arcc750.jpg",
  },
  {
    id: 13,
    name: "NVIDIA GeForce RTX 3080",
    brand: "NVIDIA",
    chipset: "RTX 3080",
    vram: "10GB GDDR6X",
    price: 699,
    stock: 15,
    rating: 4.6,
    image: "https://example.com/images/rtx3080.jpg",
  },
  {
    id: 14,
    name: "NVIDIA GeForce RTX 3070 Ti",
    brand: "NVIDIA",
    chipset: "RTX 3070 Ti",
    vram: "8GB GDDR6X",
    price: 599,
    stock: 18,
    rating: 4.5,
    image: "https://example.com/images/rtx3070ti.jpg",
  },
  {
    id: 15,
    name: "NVIDIA GeForce RTX 3060 Ti",
    brand: "NVIDIA",
    chipset: "RTX 3060 Ti",
    vram: "8GB GDDR6",
    price: 399,
    stock: 28,
    rating: 4.4,
    image: "https://example.com/images/rtx3060ti.jpg",
  },
  {
    id: 16,
    name: "NVIDIA GeForce RTX 2060",
    brand: "NVIDIA",
    chipset: "RTX 2060",
    vram: "6GB GDDR6",
    price: 249,
    stock: 40,
    rating: 4.2,
    image: "https://example.com/images/rtx2060.jpg",
  },
  {
    id: 17,
    name: "AMD Radeon RX 6700 XT",
    brand: "AMD",
    chipset: "RX 6700 XT",
    vram: "12GB GDDR6",
    price: 399,
    stock: 30,
    rating: 4.3,
    image: "https://example.com/images/rx6700xt.jpg",
  },
  {
    id: 18,
    name: "AMD Radeon RX 6600 XT",
    brand: "AMD",
    chipset: "RX 6600 XT",
    vram: "8GB GDDR6",
    price: 279,
    stock: 35,
    rating: 4.1,
    image: "https://example.com/images/rx6600xt.jpg",
  },
  {
    id: 19,
    name: "AMD Radeon RX 6500 XT",
    brand: "AMD",
    chipset: "RX 6500 XT",
    vram: "4GB GDDR6",
    price: 199,
    stock: 45,
    rating: 3.9,
    image: "https://example.com/images/rx6500xt.jpg",
  },
  {
    id: 20,
    name: "Intel Arc A380",
    brand: "Intel",
    chipset: "Arc A380",
    vram: "6GB GDDR6",
    price: 139,
    stock: 50,
    rating: 3.8,
    image: "https://example.com/images/arcc380.jpg",
  },
];

const databro = [
  {
    id: 1,
    name: "Andi Saputra",
    username: "andisap",
    email: "andi.saputra@example.com",
    age: 25,
    city: "Jakarta",
  },
  {
    id: 2,
    name: "Budi Santoso",
    username: "budisant",
    email: "budi.santoso@example.com",
    age: 30,
    city: "Bandung",
  },
  {
    id: 3,
    name: "Citra Dewi",
    username: "citradw",
    email: "citra.dewi@example.com",
    age: 28,
    city: "Surabaya",
  },
  {
    id: 4,
    name: "Dedi Pratama",
    username: "dedipra",
    email: "dedi.pratama@example.com",
    age: 35,
    city: "Medan",
  },
  {
    id: 5,
    name: "Eka Putri",
    username: "ekaptr",
    email: "eka.putri@example.com",
    age: 22,
    city: "Yogyakarta",
  },
  {
    id: 6,
    name: "Fajar Hidayat",
    username: "fajarh",
    email: "fajar.hidayat@example.com",
    age: 27,
    city: "Malang",
  },
  {
    id: 7,
    name: "Gita Sari",
    username: "gitasari",
    email: "gita.sari@example.com",
    age: 29,
    city: "Semarang",
  },
  {
    id: 8,
    name: "Hadi Setiawan",
    username: "hadistw",
    email: "hadi.setiawan@example.com",
    age: 32,
    city: "Palembang",
  },
  {
    id: 9,
    name: "Indah Lestari",
    username: "indahl",
    email: "indah.lestari@example.com",
    age: 24,
    city: "Makassar",
  },
  {
    id: 10,
    name: "Joko Widodo",
    username: "jokowi",
    email: "joko.widodo@example.com",
    age: 40,
    city: "Solo",
  },
  {
    id: 11,
    name: "Kiki Amelia",
    username: "kikiam",
    email: "kiki.amelia@example.com",
    age: 21,
    city: "Denpasar",
  },
  {
    id: 12,
    name: "Lukman Hakim",
    username: "lukmanhk",
    email: "lukman.hakim@example.com",
    age: 33,
    city: "Pontianak",
  },
  {
    id: 13,
    name: "Maya Kartika",
    username: "mayakrt",
    email: "maya.kartika@example.com",
    age: 26,
    city: "Balikpapan",
  },
  {
    id: 14,
    name: "Nanda Saputri",
    username: "nandas",
    email: "nanda.saputri@example.com",
    age: 23,
    city: "Banjarmasin",
  },
  {
    id: 15,
    name: "Oki Prabowo",
    username: "okiprb",
    email: "oki.prabowo@example.com",
    age: 31,
    city: "Padang",
  },
  {
    id: 16,
    name: "Putri Ayu",
    username: "putriayu",
    email: "putri.ayu@example.com",
    age: 28,
    city: "Pekanbaru",
  },
  {
    id: 17,
    name: "Rudi Hartono",
    username: "rudih",
    email: "rudi.hartono@example.com",
    age: 34,
    city: "Manado",
  },
  {
    id: 18,
    name: "Sinta Marlina",
    username: "sintam",
    email: "sinta.marlina@example.com",
    age: 22,
    city: "Samarinda",
  },
  {
    id: 19,
    name: "Tono Susanto",
    username: "tonoss",
    email: "tono.susanto@example.com",
    age: 29,
    city: "Ambon",
  },
  {
    id: 20,
    name: "Uli Puspita",
    username: "ulipsp",
    email: "uli.puspita@example.com",
    age: 27,
    city: "Jayapura",
  },
];
